### ISSUE TITLE
how do you implement int8 mm on cuda?

### ISSUE THREAD

**Issue by ThisisBillhe** [pytorch-labs/ao#34]
Does Torch already support int8 mm on cuda? Also, what version of torch can run torch now?

**Comment by HDCharles** [comment]
yeah as seen here:

https://github.com/pytorch-labs/ao/blob/main/torchao/quantization/quant_primitives.py#L84

but the kernel is kind of a mess (note the error checking above that line) so we combine this with torch.compile because the resulting triton kernel from [here](https://github.com/pytorch/pytorch/blob/3c77a3ed0376d894222257ff8a0060bced8fa505/torch/_inductor/kernel/mm.py#L159) and [here](https://github.com/pytorch/pytorch/blob/3c77a3ed0376d894222257ff8a0060bced8fa505/torch/_inductor/kernel/mm.py#L32)

requires less error checking and is comparably fast.

This has been available for a while, both the current stable and nightly
